functional:
  - Сайт должен предоставлять возможность регистрации и авторизации пользователей.
  - Сайт должен обеспечивать поиск и фильтрацию контента для пользователей.

non-functional:
  - Сайт должен быть оптимизирован для скорости загрузки и работы (время загрузки страницы не более 2 секунд).
  - Сайт должен быть удобен для использования на мобильных устройствах с различными разрешениями экранов.

implicit:
  - Сайт должен обеспечивать хранение и защиту персональных данных пользователей в соответствии с законодательством.
  - Сайт должен быть протестирован на совместимость с последними версиями основных веб-браузеров (Chrome, Firefox, Safari, Edge).
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей) без снижения производительности.
